#!/usr/bin/env python3
from pathlib import Path
R=Path(__file__).resolve().parents[1]
def rep(s,a,b,n):
 c=s.count(a)
 if c!=1: raise SystemExit(f'{n}: {c}')
 return s.replace(a,b,1)
p=R/'terminal/pro.js';s=p.read_text()
s=rep(s,"  const trade={tradeId:'P'+String(store.paper.trades.length+1).padStart(6,'0'),campaignId:c.campaignId,patternId:c.patternId,symbol,side:'long',entryTime:c.levels.find(x=>x.status==='filled')?.fillTime||c.createdAt,exitTime:nowIso(),averageEntry:c.averageEntry,exitPrice:exit,qty:c.qty,filledNotional:c.filledNotional,levelsFilled:c.levels.filter(x=>x.status==='filled').length,grossPnl:gross,fees:c.entryFees+exitFee,netPnl:net,reason,vLow:c.vLow,exitMode:c.exitMode||'target',trailActivatedAt:c.trailActivatedAt||null,trailHigh:c.trailHigh||null,trailStop:c.trailStop||null};\n  store.paper.trades.push(trade);store.paper.realizedPnl+=net;store.paper.fees+=trade.fees;ss.campaign=null;if(ss.pattern?.patternId===c.patternId)ss.pattern.status=reason;","  const trade={tradeId:'P'+String(store.paper.trades.length+1).padStart(6,'0'),campaignId:c.campaignId,patternId:c.patternId,symbol,side:'long',entryTime:c.levels.find(x=>x.status==='filled')?.fillTime||c.createdAt,exitTime:nowIso(),averageEntry:c.averageEntry,exitPrice:exit,qty:c.qty,filledNotional:c.filledNotional,levelsFilled:c.levels.filter(x=>x.status==='filled').length,levelsTotal:c.levels.length,grossPnl:gross,fees:c.entryFees+exitFee,netPnl:net,reason,vLow:c.vLow,exitMode:c.exitMode||'target',trailActivatedAt:c.trailActivatedAt||null,trailHigh:c.trailHigh||null,trailStop:c.trailStop||null};\n  if(c.trainingExampleId){const x=store.training.manualExamples.find(v=>v.id===c.trainingExampleId);if(x)Object.assign(x,{status:'closed',exitTime:trade.exitTime,exitPrice:trade.exitPrice,netPnl:trade.netPnl,reason:trade.reason,levelsFilled:trade.levelsFilled,levelsTotal:trade.levelsTotal,trailHigh:trade.trailHigh});}\n  store.paper.trades.push(trade);store.paper.realizedPnl+=net;store.paper.fees+=trade.fees;ss.campaign=null;if(ss.pattern?.patternId===c.patternId)ss.pattern.status=reason;",'outcome')
s=rep(s,"  if(!ss.campaign&&p&&p.status==='watching'){","  if(store.paper.settings.signalMode==='auto'&&!ss.campaign&&p&&p.status==='watching'){",'auto start')
old="""function renderPaper(){
  renderPaperHeader();const symbol=runtime.symbol,ss=store.paper.symbols[symbol],p=ss.pattern,c=ss.campaign;
  els.botTitle.textContent=`Galka bot · ${symbol.replace('USDT','')}`;els.botState.textContent=c?(c.status==='trailing'?'Трейлинг':c.status==='open'?'Позиция':'Лимитки'):p?'Галка найдена':'Ожидание';
  if(c){
    const trail=c.trailArmed?`<div>Максимум: <b>${price(c.trailHigh)}</b></div><div>Trailing-stop: <b class="up">${price(c.trailStop)}</b></div>`:`<div>Активация trail: <b>${price(c.reclaimPrice||c.vLow)}</b></div>`;
    els.campaignCard.innerHTML=`<div><b>${esc(c.status.toUpperCase())}</b> · V-low ${price(c.vLow)}</div><div>Средний вход: <b>${price(c.averageEntry)}</b></div><div>Выход: <b>${c.exitMode==='target'?'V-low target':'Reclaim trail'}</b></div>${trail}<div>Номинал: <b>${money(c.filledNotional)}</b> · PnL <b class="${c.unrealizedPnl>=0?'up':'down'}">${signedMoney(c.unrealizedPnl)}</b></div>`;
    els.levelsList.innerHTML=c.levels.map(l=>`<div class="level-row ${l.status==='filled'?'filled':''}"><span class="level-index">${l.index}</span><span><b>${price(l.price)}</b><small>−${l.depthPct}% · ${money(l.notional)}</small></span><b>${l.status==='filled'?'FILLED':'WAIT'}</b></div>`).join('');
    els.fillsCount.textContent=c.levels.filter(x=>x.status==='filled').length+'/6';
  }else{
    els.campaignCard.innerHTML=p?`Последняя галка: V-low <b>${price(p.vLow)}</b><br>Drop ${p.dropAtr.toFixed(2)} ATR · recovery ${(p.recovery*100).toFixed(0)}%<br><span class="muted">${esc(p.status)}</span>`:'Активной кампании нет.';
    els.levelsList.innerHTML='';els.fillsCount.textContent='0/6';
  }
  els.tradeHistory.innerHTML=store.paper.trades.length?store.paper.trades.slice().reverse().slice(0,100).map(t=>`<div class="trade-item"><div><b>${esc(t.symbol)}</b><b class="${t.netPnl>=0?'up':'down'}">${signedMoney(t.netPnl)}</b></div><small>${fmtTime(Math.floor(Date.parse(t.exitTime)/1000))} · ${esc(t.reason)} · ${t.levelsFilled}/6</small></div>`).join(''):'<div class="muted">Сделок пока нет.</div>';
}
"""
new="""function renderPaper(){
  renderPaperHeader();const symbol=runtime.symbol,ss=store.paper.symbols[symbol],p=ss.pattern,c=ss.campaign;
  els.manualExamplesCount.textContent=store.training.manualExamples.length;
  els.botTitle.textContent=`Galka ${store.paper.settings.signalMode==='manual'?'manual':'auto'} · ${symbol.replace('USDT','')}`;els.botState.textContent=c?(c.status==='trailing'?'Трейлинг':c.status==='open'?'Позиция':'Лимитки'):p?'Галка выбрана':'Ожидание';
  if(c){
    const trail=c.trailArmed?`<div>Максимум: <b>${price(c.trailHigh)}</b></div><div>Trailing-stop: <b class="up">${price(c.trailStop)}</b></div>`:`<div>Активация trail: <b>${price(c.reclaimPrice||c.vLow)}</b></div>`;
    els.campaignCard.innerHTML=`<div><b>${esc(c.status.toUpperCase())}</b> · уровень галки ${price(c.vLow)}</div><div>Источник: <b>${c.source==='manual'?'выбран вручную':'автопоиск'}</b></div><div>Средний вход: <b>${price(c.averageEntry)}</b></div><div>Выход: <b>${c.exitMode==='target'?'уровень галки':'Reclaim trail'}</b></div>${trail}<div>Номинал: <b>${money(c.filledNotional)}</b> · PnL <b class="${c.unrealizedPnl>=0?'up':'down'}">${signedMoney(c.unrealizedPnl)}</b></div>`;
    els.levelsList.innerHTML=c.levels.map(l=>`<div class="level-row ${l.status==='filled'?'filled':''}"><span class="level-index">${l.index}</span><span><b>${price(l.price)}</b><small>−${l.depthPct}% · ${money(l.notional)}</small></span><b>${l.status==='filled'?'FILLED':'WAIT'}</b></div>`).join('');
    els.fillsCount.textContent=c.levels.filter(x=>x.status==='filled').length+'/'+c.levels.length;
  }else{
    const detail=p?(p.source==='manual'?'Выбран вручную':`Drop ${num(p.dropAtr).toFixed(2)} ATR · recovery ${(num(p.recovery)*100).toFixed(0)}%`):'';
    els.campaignCard.innerHTML=p?`Последняя галка: <b>${price(p.vLow)}</b><br>${detail}<br><span class="muted">${esc(p.status)}</span>`:'Нажми «Указать галку на графике», затем коснись нужного уровня.';
    els.levelsList.innerHTML='';els.fillsCount.textContent='0';
  }
  els.tradeHistory.innerHTML=store.paper.trades.length?store.paper.trades.slice().reverse().slice(0,100).map(t=>`<div class="trade-item"><div><b>${esc(t.symbol)}</b><b class="${t.netPnl>=0?'up':'down'}">${signedMoney(t.netPnl)}</b></div><small>${fmtTime(Math.floor(Date.parse(t.exitTime)/1000))} · ${esc(t.reason)} · ${t.levelsFilled}/${t.levelsTotal||6}</small></div>`).join(''):'<div class="muted">Сделок пока нет.</div>';
}
"""
s=rep(s,old,new,'render')
s=rep(s,"  if(p)addPaperLine(p.vLow,COLORS.blue,'V-low');\n  if(c?.trailArmed&&c.trailStop)addPaperLine(c.trailStop,COLORS.red,'TRAIL STOP');\n  if(p)markers.push({time:p.vLowTime,position:'belowBar',color:COLORS.blue,shape:'circle',text:'V-low'});","  if(p)addPaperLine(p.vLow,p.source==='manual'?COLORS.orange:COLORS.blue,p.source==='manual'?'GALKA':'V-low');\n  if(c)for(const l of c.levels)addPaperLine(l.price,l.status==='filled'?COLORS.green:COLORS.gray,'L'+l.index);\n  if(c?.trailArmed&&c.trailStop)addPaperLine(c.trailStop,COLORS.red,'TRAIL STOP');\n  if(p)markers.push({time:p.vLowTime,position:'belowBar',color:p.source==='manual'?COLORS.orange:COLORS.blue,shape:'circle',text:p.source==='manual'?'GALKA':'V-low'});",'lines')
s=rep(s,"els.startingBalance.value=store.paper.settings.startingBalance;els.leverage.value=store.paper.settings.leverage;els.symbolNotional.value=store.paper.settings.symbolNotional;els.maxHours.value=store.paper.settings.maxHours;els.exitMode.value=store.paper.settings.exitMode;els.reclaimBufferPct.value=store.paper.settings.reclaimBufferPct;els.trailDistancePct.value=store.paper.settings.trailDistancePct;","els.startingBalance.value=store.paper.settings.startingBalance;els.leverage.value=store.paper.settings.leverage;els.symbolNotional.value=store.paper.settings.symbolNotional;els.maxHours.value=store.paper.settings.maxHours;els.signalMode.value=store.paper.settings.signalMode;els.ladderStepPct.value=store.paper.settings.ladderStepPct;els.manualDepthPct.value=store.paper.settings.manualDepthPct;els.exitMode.value=store.paper.settings.exitMode;els.reclaimBufferPct.value=store.paper.settings.reclaimBufferPct;els.trailDistancePct.value=store.paper.settings.trailDistancePct;",'values')
s=rep(s,"els.leftbar.onclick=e=>{const b=e.target.closest('[data-tool]');if(b)setTool(b.dataset.tool);};","els.leftbar.onclick=e=>{const b=e.target.closest('[data-tool]');if(b)setTool(b.dataset.tool);};\nels.manualGalkaBtn.onclick=()=>{setTool('manualGalka');els.sidebar.classList.remove('open');toast('Коснись уровня галки на графике');};\nels.cancelManualGalka.onclick=cancelManualSelection;els.exportManualExamples.onclick=exportManualExamples;",'events')
oldsave="els.savePaperSettings.onclick=()=>{const s=store.paper.settings;s.startingBalance=Math.max(100,num(els.startingBalance.value,1000));s.leverage=clamp(num(els.leverage.value,10),1,20);s.symbolNotional=clamp(num(els.symbolNotional.value,3333.33),100,10000);s.maxHours=clamp(num(els.maxHours.value,72),1,336);s.exitMode=els.exitMode.value==='target'?'target':'trail';s.reclaimBufferPct=clamp(num(els.reclaimBufferPct.value,.10),0,5);s.trailDistancePct=clamp(num(els.trailDistancePct.value,.75),.05,10);save();renderPaper();toast('Paper-настройки сохранены');};"
newsave="els.savePaperSettings.onclick=()=>{const s=store.paper.settings;s.startingBalance=Math.max(100,num(els.startingBalance.value,1000));s.leverage=clamp(num(els.leverage.value,10),1,20);s.symbolNotional=clamp(num(els.symbolNotional.value,400),50,10000);s.maxHours=clamp(num(els.maxHours.value,72),1,336);s.signalMode=els.signalMode.value==='auto'?'auto':'manual';s.ladderStepPct=clamp(num(els.ladderStepPct.value,.15),.05,2);s.manualDepthPct=clamp(num(els.manualDepthPct.value,1.5),s.ladderStepPct,10);s.exitMode=els.exitMode.value==='target'?'target':'trail';s.reclaimBufferPct=clamp(num(els.reclaimBufferPct.value,.10),0,5);s.trailDistancePct=clamp(num(els.trailDistancePct.value,.75),.05,10);save();renderPaper();updateMarkers();toast('Paper-настройки сохранены');};"
s=rep(s,oldsave,newsave,'save')
p.write_text(s)
p=R/'scripts/check-pro-terminal.mjs';s=p.read_text()
s=rep(s,"  ['paper account', /startingBalance:1000/.test(js) && /symbolNotional:3333\\.33/.test(js)],","  ['paper account', /startingBalance:1000/.test(js) && /symbolNotional:400/.test(js)],",'check account')
s=rep(s,"  ['reclaim trailing exit', /id=\"exitMode\"/.test(html) && /trailDistancePct:0\\.75/.test(js) && /reclaim_trailing_stop/.test(js)],","  ['reclaim trailing exit', /id=\"exitMode\"/.test(html) && /trailDistancePct:0\\.75/.test(js) && /reclaim_trailing_stop/.test(js)],\n  ['manual Galka selector', /data-tool=\"manualGalka\"/.test(html) && /setManualGalka/.test(js) && /id=\"manualGalkaBtn\"/.test(html)],\n  ['0.15 percent ladder', /ladderStepPct:0\\.15/.test(js) && /id=\"manualDepthPct\"/.test(html) && /campaignLadder/.test(js)],\n  ['manual training examples', /manualExamples/.test(js) && /exportManualExamples/.test(js) && /id=\"manualExamplesCount\"/.test(html)],",'checks')
p.write_text(s)
